{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kube-dump.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "kube-dump.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        spec:
          serviceAccountName: {{ include "kube-dump.serviceAccountName" . }}
          containers:
            - name: {{ include "kube-dump.chart" . }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              securityContext:
                runAsUser: 100
                runAsGroup: 101
              command:
                - "/bin/sh"
                - "-c"
                - |
                  {{- if .Values.git.sshKey }}
                  cp /etc/git-ssh/ssh-key ~/.ssh/id_rsa && \
                  chmod 600 ~/.ssh/id_rsa && \
                  {{- end }}
                  ./kube-dump 
              env:
                - name: MODE
                  value: {{ .Values.dump.mode | default "dump" | quote }}
                - name: DESTINATION_DIR
                  value: {{ .Values.dump.destinationDir | default "/data" | quote }}
                - name: FORCE_REMOVE
                  value: {{ .Values.dump.forceRemove | default false | quote }}
                - name: DETAILED
                  value: {{ .Values.dump.detailed | default false | quote }}
                - name: OUTPUT_BY_TYPE
                  value: {{ .Values.dump.outputByType | default true | quote }}
                - name: FLAT
                  value: {{ .Values.dump.flat | default false | quote }}
                - name: IGNORE_CLUSTER_INFO
                  value: {{ .Values.dump.ignoreClusterInfo | default false | quote }}
                - name: OUTPUT_FORMAT
                  value: {{ .Values.output.format | default "yaml" | quote }}
                - name: NAMESPACES
                  value: {{ join "," .Values.kubernetes.namespaces | default "" | quote }}
                - name: NAMESPACED_RESOURCES
                  value: {{ join "," .Values.kubernetes.namespacedResources | default "" | quote }}
                - name: CLUSTER_RESOURCES
                  value: {{ join "," .Values.kubernetes.clusterResources | default "" | quote }}
                - name: KUBE_CONFIG
                  value: {{ .Values.kubernetes.kubeConfig | default "" | quote }}
                - name: KUBE_CONTEXT
                  value: {{ .Values.kubernetes.kubeContext | default "" | quote  }}
                - name: KUBE_CLUSTER
                  value: {{ .Values.kubernetes.kubeCluster | default "" | quote }}
                - name: KUBE_INSECURE_TLS
                  value: {{ .Values.kubernetes.kubeInsecureTls | default false | quote }}
                - name: GIT_COMMIT
                  value: {{ .Values.git.commit | default false | quote }}
                - name: GIT_PUSH
                  value: {{ .Values.git.push | default false | quote }}
                - name: GIT_BRANCH
                  value: {{ .Values.git.branch | default "main" | quote }}
                - name: GIT_COMMIT_USER
                  value: {{ .Values.git.commitUser | default "kube-dump" | quote }}
                - name: GIT_COMMIT_EMAIL
                  value: {{ .Values.git.commitEmail | default "kube-dump@example.com" | quote }}
                - name: GIT_REMOTE_NAME
                  value: {{ .Values.git.remoteName | default "origin" | quote }}
                - name: GIT_REMOTE_URL
                  value: {{ .Values.git.remoteUrl | default "" | quote }}
                - name: ARCHIVE_ENABLED
                  value: {{ .Values.archive.enabled | default false | quote }}
                - name: ARCHIVE_TYPE
                  value: {{ .Values.archive.type | default "xz" | quote }}
                - name: ARCHIVE_ROTATE_DAYS
                  value: {{ .Values.archive.rotateDays | default 60 | quote }}
              volumeMounts:
                {{- if .Values.pvc.enabled }}
                - name: data
                  mountPath: /data
                {{- end }}
                {{- if .Values.git.sshKey }}
                - name: git-ssh
                  mountPath: /etc/git-ssh
                  readOnly: true
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            {{- if .Values.pvc.enabled }}
            - name: data
              persistentVolumeClaim:
                claimName: {{ include "kube-dump.name" . }}-data
            {{- else }}
            - name: data
              emptyDir: {}
            {{- end }}
            {{- if .Values.git.sshKey }}
            - name: git-ssh
              secret:
                secretName: {{ .Values.git.sshKeySecretName }}
                items:
                  - key: ssh-key
                    path: ssh-key
                    mode: 0666
            {{- end }}
          restartPolicy: OnFailure
{{- end }}
