{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kube-dump.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "kube-dump.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClass | default "standard" }}
{{- end }}
