{{- if .Values.git.sshKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-dump.fullname" . }}-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "kube-dump.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  ssh-key: {{ .Values.git.sshKey | b64enc | quote }}
{{- end }}
