{{- if .Values.git.sshKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-dump.fullname" . }}-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "kube-dump.labels" . | nindent 4 }}
type: Opaque
data:
  ssh-key: {{ .Values.git.sshKey | b64enc | quote }}
{{- end }}
